packages:
  - '.'
allowBuilds:
  '@clerk/shared': true
  bufferutil: true
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - sst-darwin-arm64@4.17.0
  - sst-darwin-x64@4.17.0
  - sst-linux-arm64@4.17.0
  - sst-linux-x64@4.17.0
  - sst-linux-x86@4.17.0
  - sst-win32-arm64@4.17.0
  - sst-win32-x64@4.17.0
  - sst-win32-x86@4.17.0
  - sst@4.17.0
