/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DeepgramApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Dynamoshapikeys": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshbetawaitlist": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshconsentrecords": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshdeletionrequests": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshintegrations": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshlabels": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshmeetings": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshmilestones": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshnotifications": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshorgaccessrequests": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshorginvites": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshorgmetadata": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshprojectmembers": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshprojects": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshspecs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshsprints": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshticketactivities": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshticketattachments": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshticketcomments": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshticketdeps": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshtickets": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Dynamoshusers": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GoogleOauthClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GroqApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Site": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "SkribbyApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SkribbyWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TokenEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "WebhookAccessToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}