// lib/shipai/github.ts

const BASE = 'https://api.github.com';

function headers() {
  return {
    Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  };
}

function repoPath(overrides: { owner?: string; repo?: string } = {}) {
  const owner = overrides.owner || process.env.GITHUB_OWNER;
  const repo = overrides.repo || process.env.GITHUB_REPO;
  return `${BASE}/repos/${owner}/${repo}`;
}

async function githubFetch(url: string, options: RequestInit = {}) {
  const res = await fetch(url, {
    ...options,
    headers: { ...headers(), ...(options.headers as any) },
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`GitHub API error (${res.status}): ${err.message || res.statusText}`);
  }
  return res.json();
}

async function getDefaultBranchSha(overrides = {}) {
  const repo = await githubFetch(repoPath(overrides));
  const defaultBranch = repo.default_branch;
  const ref = await githubFetch(`${repoPath(overrides)}/git/refs/heads/${defaultBranch}`);
  return ref.object.sha;
}

export async function createGithubIssue(title: string, body: string, overrides = {}) {
  return githubFetch(`${repoPath(overrides)}/issues`, {
    method: 'POST',
    body: JSON.stringify({ title, body }),
  });
}

export async function createBranch(branchName: string, overrides = {}) {
  const sha = await getDefaultBranchSha(overrides);
  return githubFetch(`${repoPath(overrides)}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha }),
  });
}

async function getFileSha(
  filePath: string,
  branch: string,
  overrides = {}
): Promise<string | null> {
  try {
    const res = await fetch(`${repoPath(overrides)}/contents/${filePath}?ref=${branch}`, {
      headers: headers(),
    });
    if (res.status === 404) return null;
    const data = await res.json();
    return data.sha;
  } catch {
    return null;
  }
}

export async function commitFile(
  filePath: string,
  content: string,
  branch: string,
  overrides: any = {}
) {
  const encodedContent = Buffer.from(content, 'utf-8').toString('base64');
  const existingSha = await getFileSha(filePath, branch, overrides);
  const commitMessage = overrides.commitMessage || `feat: add ${filePath}`;

  const payload: any = { message: commitMessage, content: encodedContent, branch };
  if (existingSha) payload.sha = existingSha;

  return githubFetch(`${repoPath(overrides)}/contents/${filePath}`, {
    method: 'PUT',
    body: JSON.stringify(payload),
  });
}

export async function createPullRequest(title: string, branch: string, overrides = {}) {
  const repo = await githubFetch(repoPath(overrides));
  return githubFetch(`${repoPath(overrides)}/pulls`, {
    method: 'POST',
    body: JSON.stringify({
      title,
      head: branch,
      base: repo.default_branch,
      body: `## Summary\n\nThis pull request was automatically generated by **Syntheon AI**.\n\n**Branch:** \`${branch}\``,
    }),
  });
}

// ─── NEW: Fetch file tree from GitHub ──────────────────────────
export async function getRepoFileTree(
  overrides: { owner?: string; repo?: string } = {}
): Promise<string[]> {
  try {
    // Get default branch
    const repo = await githubFetch(repoPath(overrides));
    const defaultBranch = repo.default_branch;

    // Get the full recursive tree
    const ref = await githubFetch(`${repoPath(overrides)}/git/refs/heads/${defaultBranch}`);
    const sha = ref.object.sha;
    const tree = await githubFetch(`${repoPath(overrides)}/git/trees/${sha}?recursive=1`);

    // Return only file paths, excluding .github folder
    return tree.tree
      .filter((item: any) => item.type === 'blob' && !item.path.startsWith('.github'))
      .map((item: any) => item.path);
  } catch (err) {
    console.error('Failed to fetch file tree:', err);
    return [];
  }
}

// ─── NEW: Fetch specific file contents from GitHub ─────────────
export async function getFileContents(
  filePaths: string[],
  overrides: { owner?: string; repo?: string } = {}
): Promise<Record<string, string>> {
  const contents: Record<string, string> = {};

  await Promise.all(
    filePaths.map(async (filePath) => {
      try {
        const res = await fetch(`${repoPath(overrides)}/contents/${filePath}`, {
          headers: headers(),
        });
        if (!res.ok) return;
        const data = await res.json();
        const decoded = Buffer.from(data.content, 'base64').toString('utf-8');
        contents[filePath] = decoded;
      } catch {
        console.error(`Failed to fetch file: ${filePath}`);
      }
    })
  );

  return contents;
}

// ─── NEW: Get repo owner and name from env ─────────────────────
export function getRepoInfo() {
  return {
    owner: process.env.GITHUB_OWNER!,
    repo: process.env.GITHUB_REPO!,
  };
}
